FROM postgres:15-alpine

# Set environment variables
ENV POSTGRES_USER=novikaway
ENV POSTGRES_PASSWORD=yourpassword
ENV POSTGRES_DB=yourdatabase

# Add any custom initialization scripts
COPY ./init-db.sql /docker-entrypoint-initdb.d/

# Expose PostgreSQL port
EXPOSE 5432
