services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: novikaway/home-library:latest
    container_name: home-library-app
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=nestuser
      - DB_PASSWORD=SecureP@ssw0rd!
      - DB_DATABASE=homelibrarydb
      # Другие переменные окружения
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:15-alpine
    container_name: home-library-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=nestuser
      - POSTGRES_PASSWORD=SecureP@ssw0rd!
      - POSTGRES_DB=homelibrarydb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
